import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

console.log('Building player...');

// Run vite build with the player config
try {
    execSync('npx vite build -c vite.player.config.ts', { stdio: 'inherit' });
} catch (e) {
    console.error('Build failed', e);
    process.exit(1);
}

const distDir = path.resolve(__dirname, '../dist/player/assets');
const outputDir = path.resolve(__dirname, '../src/assets');

if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
}

// Find the JS and CSS files
const files = fs.readdirSync(distDir);
const jsFile = files.find(f => f.endsWith('.js') && f.includes('player'));
const cssFile = files.find(f => f.endsWith('.css') && f.includes('player')); // CSS might be named differently or attached to player

if (!jsFile) {
    console.error('Could not find built JS file');
    process.exit(1);
}

const jsContent = fs.readFileSync(path.join(distDir, jsFile), 'utf-8');
const cssContent = cssFile ? fs.readFileSync(path.join(distDir, cssFile), 'utf-8') : '';

const tsContent = `// Auto-generated by scripts/embed-player.js
export const PLAYER_JS = ${JSON.stringify(jsContent)};
export const PLAYER_CSS = ${JSON.stringify(cssContent)};
`;

fs.writeFileSync(path.join(outputDir, 'player-assets.ts'), tsContent);

console.log(`Player assets embedded into src/assets/player-assets.ts (${(jsContent.length / 1024).toFixed(2)} KB JS, ${(cssContent.length / 1024).toFixed(2)} KB CSS)`);
